Repository someone-to-speak/OnePeak, pull requests merged in 2024-11, with the labels that each got.

#47 Feat/chat bot
  .eslintrc.json
  database.types.ts
  package.json
  src/api/supabase/user.ts
  src/app/(mobile)/chatbot/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/api/api.ts
  src/app/types/chatBotType/chatBotType.ts
  src/components/BottomSheetModal.tsx
  src/components/chatBot/aiTutorHome/TodayLearn.tsx
  src/components/chatBot/chat/ChatInput.tsx
  src/components/chatBot/chat/ChatMessageList.tsx
  src/hooks/getUserInfo.ts
  src/hooks/useAudioRecorder.ts
  src/hooks/useChatMessages.ts
  src/pages/api/openai.ts
  src/pages/api/whisper.ts
  src/services/supabaseAuth.ts
  src/type.ts
  src/utils/chatbot/chatBotApi.ts
  src/utils/chatbot/date.ts
Labels: 수정, 새 기능

#48 Style- global.css/tailwind.config
  src/app/globals.css
  src/utils/notifications/sendPush.ts
  tailwind.config.ts
Labels: 공지, 스타일

#50 Feat/login info
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/app/(mobile)/loginInfo/setNickname/page.tsx
Labels: 새 기능

#54 add:푸쉬알람동의여부버튼
  package.json
  public/service-worker.js
  src/app/(desktop)/admin/alarmManagement/page.tsx
  src/app/(mobile)/layout.tsx
  src/app/(mobile)/loginInfo/setIsNotice/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/globals.css
  src/components/notification/NotificationButton.tsx
  src/components/serviceWorker/ServiceWorkerLoader.tsx
  src/utils/notifications/notifications.ts
  src/utils/notifications/pushSubscription.ts
  tailwind.config.ts
Labels: 수정, 새 기능

#96 Style/chal
  package.json
  src/app/(mobile)/challenge/grammar/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/grammar/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/grammar/result/page.tsx
  src/app/(mobile)/challenge/grammar/wrongAnswerNote/page.tsx
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/word/result/page.tsx
  src/app/(mobile)/challenge/word/wrongAnswerNote/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/page.tsx
  src/assets/active-check.svg
  src/assets/bell-ringing.svg
  src/assets/calendar.svg
  src/assets/check-icon.svg
  src/assets/close-icon.svg
  src/assets/logo-icon.svg
  src/assets/noactive-check.svg
  src/assets/not-answer.svg
  src/assets/result/result-0.svg
  src/assets/result/result-1.svg
  src/assets/result/result-2.svg
  src/assets/result/result-3.svg
  src/components/challenge/RandomEnglishGrammarQuiz.tsx
  src/components/challenge/RandomEnglishWordQuiz.tsx
  src/components/challenge/RandomKoreanGrammarQuiz.tsx
  src/components/challenge/RandomKoreanWordQuiz.tsx
  src/components/header/Header.tsx
  src/components/ui/NoIconHeader.tsx
  src/components/ui/WithIconHeader.tsx
  src/components/wrongAnswer/GrammarList.tsx
  src/components/wrongAnswer/WordList.tsx
  tailwind.config.ts
Labels: 스타일

#101 fix app icon
  public/app-icon.png
  public/icon-192x192.png
  public/icon-512x512.png
  public/service-worker.js
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/layout.tsx
  src/app/manifest.ts
  src/assets/app-icon.png
Labels: 스타일

#108 fix: 배포 환경 오류 해결
  src/utils/chatbot/chatBotApi.ts
Labels: 수정

#109 Style/chal
  public/service-worker.js
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/api/(challange)/fetchWordQuiz/route.ts
  src/app/api/grammar/route.ts
  src/components/challenge/Quiz.tsx
  src/components/challenge/RandomEnglishGrammarQuiz.tsx
  src/components/challenge/RandomEnglishWordQuiz.tsx
  src/components/challenge/RandomKoreanGrammarQuiz.tsx
  src/components/challenge/RandomKoreanWordQuiz.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/myPage/LanguageSelectorToggle.tsx
  src/components/myPage/UserProfile.tsx
  src/components/ui/NoIconHeader.tsx
  src/components/ui/WithIconHeader.tsx
  src/components/ui/button/index.tsx
  src/components/ui/toggle/notificationToggle.tsx
  src/components/ui/typography/index.tsx
  src/components/ui/userProfile/index.tsx
  src/components/wrongAnswer/GrammarList.tsx
  src/components/wrongAnswer/WordList.tsx
  src/utils/notifications/pushSubscription.ts
Labels: 스타일

#117 Style/chal
  src/app/(mobile)/challenge/grammar/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/grammar/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/grammar/page.tsx
  src/app/(mobile)/challenge/grammar/result/page.tsx
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/word/result/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/assets/result/one-point.svg
  src/assets/result/three-point.svg
  src/assets/result/two-point.svg
  src/assets/result/zero-point.svg
  src/components/challenge/FetchGrammarQuizButton.tsx
  src/components/challenge/FetchWordQuizButton.tsx
  src/components/challenge/Quiz.tsx
  src/components/myPage/UserProfile.tsx
  src/hooks/useLanguages.ts
  src/hooks/useNotifications.ts
  src/hooks/useProblems.ts
  src/hooks/useQuiz.ts
  src/hooks/useSlider.ts
  src/hooks/useSubscription.ts
  src/hooks/useUserInfo.ts
  src/hooks/useUserProfile.ts
Labels: 수정, 스타일

#122 fix header for Tablet ver.
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/globals.css
  src/components/header/Header.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/ui/NavbarGnb.tsx
  src/components/ui/NoIconHeader.tsx
  src/components/ui/WithIconHeader.tsx
  src/components/ui/typography/index.tsx
  src/utils/notifications/pushSubscription.ts
Labels: 수정, 스타일

#127 Style/chatbot
  database.types.ts
  src/app/(mobile)/attendance/page.tsx
  src/app/(mobile)/page.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/DateGrid.tsx
  src/components/calendar/DayHeader.tsx
  src/components/chatBot/aiTutorHome/CustomizedLearn.tsx
  src/components/chatBot/aiTutorHome/Reviewing.tsx
  src/components/chatBot/aiTutorHome/TodayLearn.tsx
  src/components/chatBot/review/ReviewList.tsx
  src/components/newCalendar/NewCalendar.tsx
Labels: 작업 예정, 스타일

#128 Style/chal
  package.json
  src/app/(mobile)/challenge/grammar/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/grammar/result/page.tsx
  src/app/(mobile)/layout.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/components/challenge/Quiz.tsx
  src/components/header/Header.tsx
  src/components/notificationPopup/NotificationBell.tsx
  src/components/notificationPopup/NotificationPopup.tsx
  src/components/ui/button/index.tsx
  src/components/ui/userProfile/index.tsx
Labels: 수정, 스타일

#131 Style/chal
  src/app/(mobile)/challenge/grammar/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/grammar/result/page.tsx
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/korean/page.tsx
  src/app/(mobile)/challenge/word/result/page.tsx
  src/app/(mobile)/layout.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/(mobile)/page.tsx
  src/assets/user-icon.svg
  src/components/challenge/Quiz.tsx
  src/components/notificationPopup/NotificationBell.tsx
  src/components/ui/LoadingSpinner.tsx
  src/components/ui/header/Header.tsx
  src/components/ui/header/HeaderTop.tsx
  src/hooks/useNotifications.ts
  src/hooks/useSlider.ts
Labels: 스타일

#133 style: Footer 컴포넌트 생성 및 레이아웃 적용
  src/app/(mobile)/layout.tsx
  src/components/ui/footer/Footer.tsx
Labels: 스타일

#134 Style/chal
  src/app/(mobile)/challenge/grammar/result/page.tsx
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/challenge/word/result/page.tsx
  src/app/(mobile)/layout.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/(mobile)/page.tsx
  src/components/challenge/Quiz.tsx
  src/components/ui/header/HeaderTop.tsx
  src/components/wrongAnswer/GrammarList.tsx
Labels: 새 기능

#137 Style/wrong answer note
  src/app/(mobile)/challenge/grammar/wrongAnswerNote/page.tsx
  src/components/wrongAnswer/GrammarList.tsx
Labels: 스타일

#140 style: 언어수업 첫페이지 반응형 작업 수정
  src/app/(mobile)/lesson/page.tsx
  src/components/ui/header/HeaderTop.tsx
Labels: 수정, 스타일

#141 Style/wrong answer note
  src/components/wrongAnswer/GrammarList.tsx
  src/components/wrongAnswer/WordList.tsx
Labels: 수정, 스타일

#147 Style/chatbot
  src/app/(mobile)/chatbot/page.tsx
  src/components/ChatModal.tsx
  src/components/chatBot/aiTutorHome/CustomizedLearn.tsx
Labels: 작업 예정, 스타일

#151 fix lesson, add toast
  package.json
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/lesson/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/chatBot/aiTutorHome/TodayLearn.tsx
  src/components/myPage/UserProfile.tsx
  src/components/notificationPopup/NotificationPopup.tsx
  src/components/ui/LoadingSpinner.tsx
  src/components/ui/SpinnerButton.tsx
  src/components/ui/footer/Footer.tsx
  src/components/ui/header/Header.tsx
  src/components/ui/toast/ConfirmToast.tsx
  src/components/ui/userProfile/index.tsx
  src/components/wrongAnswer/GrammarList.tsx
  src/utils/myPage/cancelAccount.ts
  src/utils/myPage/logout.ts
Labels: 수정, 스타일

#152 style: 오픈 예정 알림 모달 추가
  src/app/(mobile)/page.tsx
  src/components/ChatModal.tsx
  src/components/chatBot/aiTutorHome/CustomizedLearn.tsx
  src/components/chatBot/review/ReviewList.tsx
  src/components/ui/header/Header.tsx
  src/components/ui/header/HeaderTop.tsx
  src/utils/chatbot/date.ts
Labels: 새 기능, 스타일

#160 Dev
  src/components/chatBot/aiTutorHome/TodayLearn.tsx
  src/utils/supabase/middleware.ts
Labels: 배포

#161 fix logIn , Header, Gnb
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/ui/NavbarGnb.tsx
  src/components/ui/header/Header.tsx
Labels: 수정, 스타일

#164 회원가입 시 닉네임 입력 페이지로 이동하는 오류 해결
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
Labels: 배포

#166 Dev
  src/app/(mobile)/chat/page.tsx
  src/app/(mobile)/chat/room/_components/InputField.tsx
  src/app/global-error.tsx
  src/services/supabaseAuth.ts
Labels: 배포

#168 Dev
  src/api/supabase/chat.ts
Labels: 배포

#171 배포용 PR
  src/app/(mobile)/challenge/word/(quiz)/english/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/korean/page.tsx
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/components/BottomSheetModal.tsx
  src/components/ChatModal.tsx
Labels: 배포

#173 Feat/login info
  src/api/firstSetting/fetchMyLanguage.ts
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/components/ui/SpinnerButton.tsx
Labels: 수정

#175 Dev
  src/api/firstSetting/fetchMyLanguage.ts
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/components/ui/SpinnerButton.tsx
Labels: 배포

#181 Style/chatbot
  src/components/chatBot/chat/ChatInput.tsx
  src/hooks/useAudioRecorder.ts
Labels: 수정

#182 Dev
  src/components/chatBot/chat/ChatInput.tsx
  src/hooks/useAudioRecorder.ts
  src/services/supabaseAuth.ts
Labels: 배포

#189 Fix/chatbot
  src/app/api/(chatBot)/speechToText/route.ts
  src/components/chatBot/chat/ChatInput.tsx
  src/components/chatBot/chat/ChatMessageList.tsx
  src/hooks/useAudioRecorder.ts
  src/hooks/useChatMessages.ts
  src/pages/api/whisper.ts
  src/utils/chatbot/chatBotApi.ts
Labels: 수정

#190 fix: 경로 재변경 및 let 변수 제거
  src/app/api/chatBotSpeechToText/route.ts
  src/utils/chatbot/chatBotApi.ts
Labels: 수정

#193 test: iOS에서 STT 안 되는 문제 해결을 위한 테스트
  src/hooks/useAudioRecorder.ts
  src/utils/chatbot/chatBotApi.ts
Labels: 오류, 작업 예정

#192 add modal fix Quiz
  src/app/(mobile)/myPage/(Detail)/faq/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/components/ChatModal.tsx
  src/components/challenge/Quiz.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/ui/toast/ConfirmToast.tsx
  src/components/ui/userProfile/index.tsx
  src/hooks/useQuiz.ts
  src/hooks/useUser.ts
  src/utils/myPage/cancelAccount.ts
  src/utils/myPage/updateLanguage.ts
Labels: 수정

#194 Fix/chatbot
  package.json
  src/app/(mobile)/chatbot/page.tsx
  src/hooks/useAudioRecorder.ts
Labels: 공지, 오류 해결

#204 Fix/chatbot
  src/app/api/chatBotMessage/route.ts
  src/app/api/chatBotSpeechToText/route.ts
  src/components/chatBot/chat/ChatInput.tsx
  src/utils/chatbot/chatBotApi.ts
Labels: 수정

#208 style: 디자인 QA 반영
  src/app/(mobile)/chatbot/page.tsx
  src/components/calendar/CalendarHeader.tsx
  src/components/chatBot/aiTutorHome/TodayLearn.tsx
  src/components/chatBot/chat/ChatInput.tsx
  src/components/chatBot/review/ReviewItem.tsx
  src/components/chatBot/review/ReviewList.tsx
Labels: 스타일

#209 technologist: 주석추가
  src/api/openAI/tts.ts
  src/app/(mobile)/lesson/page.tsx
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/app/(mobile)/loginInfo/setNickname/page.tsx
  src/app/api/textToSpeech/route.ts
  src/components/ui/SpinnerButton.tsx
  src/components/wrongAnswer/GrammarList.tsx
  src/components/wrongAnswer/WordList.tsx
Labels: 주석추가

#206 fix QA
  package.json
  src/app/(desktop)/admin/languageManagement/page.tsx
  src/app/(mobile)/challenge/grammar/(quiz)/English/page.tsx
  src/app/(mobile)/challenge/grammar/(quiz)/Korean/page.tsx
  src/app/(mobile)/challenge/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/English/page.tsx
  src/app/(mobile)/challenge/word/(quiz)/Korean/page.tsx
  src/app/(mobile)/challenge/word/result/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/myPage/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/api/(challange)/fetchGrammarQuiz/route.ts
  src/app/api/(challange)/fetchWordQuiz/route.ts
  src/components/AccordionItem.tsx
  src/components/CountriesSelect.tsx
  src/components/CountrySelect.tsx
  src/components/MaterialTailwindWrapper.tsx
  src/components/admin/languageManagement/LanguageTable.tsx
  src/components/challenge/Quiz.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/notificationPopup/NotificationPopup.tsx
  src/components/ui/userProfile/index.tsx
  src/hooks/useQuiz.ts
  types/use-react-countries.d.ts
Labels: 수정, 스타일

#211 fix build error
  package.json
  src/app/globals.css
Labels: 수정

#212 del nextui del toastify
  package.json
  src/app/(mobile)/loginInfo/setLearnLanguage/page.tsx
  src/app/(mobile)/loginInfo/setMyLanguage/page.tsx
  src/app/(mobile)/myPage/editProfile/page.tsx
  src/app/(mobile)/notifications/page.tsx
  src/app/layout.tsx
  src/components/AccordionItem.tsx
Labels: 수정

#213 fix: build 오류 해결
  src/components/CountriesSelect.tsx
Labels: 오류 해결

#219 Dev
  package.json
  src/api/supabase/admin.ts
  src/api/supabase/chat.ts
  src/app/(desktop)/admin/blockManagement/[blockedUserId]/page.tsx
  src/app/(desktop)/admin/blockManagement/page.tsx
  src/app/(desktop)/admin/faqManagement/[faqId]/page.tsx
  src/app/(desktop)/admin/faqManagement/page.tsx
  src/app/(desktop)/admin/languageManagement/page.tsx
  src/app/(desktop)/admin/page.tsx
  src/app/(desktop)/admin/quizManagement/page.tsx
  src/app/(desktop)/admin/userManagement/page.tsx
  src/app/(mobile)/Matching.tsx
  src/app/(mobile)/challenge/word/page.tsx
  src/app/(mobile)/chat/page.tsx
  src/app/(mobile)/chat/report/page.tsx
  src/app/(mobile)/lesson/room/page.tsx
  src/app/(mobile)/myPage/(Detail)/settings/page.tsx
  src/app/test/page.tsx
  src/components/CountriesSelect.tsx
  src/components/CountrySelect.tsx
  src/components/admin/PageNationUI.tsx
  src/components/admin/faqManagement/faqTable.tsx
  src/components/challenge/FetchGrammarQuizButton.tsx
  src/components/challenge/FetchWordQuizButton.tsx
  src/components/myPage/LanguageSelectorDropDown.tsx
  src/components/ui/icon/Icons.tsx
  src/components/ui/icon/index.tsx
  src/hooks/useCallerCallee.ts
  src/hooks/useMatching.ts
  src/hooks/useMessage.ts
  src/hooks/useQuiz.ts
  src/hooks/useUpdateProfile.ts
  src/hooks/useWebRTC.ts
  src/services/webrtcService.ts
  src/type.ts
  src/utils/media/index.ts
  src/utils/myPage/imageUpload.ts
  src/utils/myPage/updateLanguage.ts
  src/utils/notifications/pushSubscription.ts
  types/use-react-countries.d.ts
Labels: 배포

#223 main 최신화
  src/api/supabase/admin.ts
  src/app/(desktop)/admin/userManagement/page.tsx
  src/app/(mobile)/chat/report/page.tsx
  src/app/(mobile)/myPage/(Detail)/faq/page.tsx
  src/components/ChatModal.tsx
  src/components/admin/usersManagement/UsersTable.tsx
Labels: 배포

#230 Dev
  README.md
Labels: 배포
